### ISSUE TITLE
Is IE 11 support anyhow possible?

### ISSUE THREAD

**Issue by tom94zoe** [IMM9O/ng-custom-element#1]
Hi, 

I have read your medium article. 
I tried mutliple solutions/tutorials for creating an angular web component, yours was the easiest.

Anyway I need is a solution to get the angular elements running with Internet Explorer 11.
Have you found a solution for that issue? 

thank you in advance

**Comment by IMM9O** [comment]
Hi @tom94zoe 
Have you try to include some polyfills

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
 import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/set';

Or Check this link

https://stackoverflow.com/questions/35140718/angular-2-4-5-not-working-in-ie11

**Comment by tom94zoe** [comment]
Hi @IMM9O, 

Thank you for the fast responds.
I tried it. 

I also cloned your repo, and tried it with your code. After building elements, you see nothing of them.

**Comment by IMM9O** [comment]
Hi @tom94zoe 

Sorry for late, I will check with my side, but i think if the project not working on IE, it will not work as according to angular.io "Angular supports most recent browsers including ( IE11 )"

https://angular.io/guide/browser-support

And i remember if you want to support IE11 all you do to uncomment polyfils included in polyfills file under  this component

```js
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
```

any way i will check and back to you

**Comment by IMM9O** [comment]
H @tom94zoe 
Back to you :),  it seems that IE not supported web component natively
See first this link from angular.io

https://angular.io/guide/elements#browser-support-for-custom-elements

I make it work by adding this polyfills
```js

 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/es6/reflect';

```  
don't forget to install this package first

```bash
npm install --save classlist.js
```

And change component encapsulation mode from `Native` to `Emulated`
May be you loose the advantage of shadow dom but at least it works on IE11

**Comment by tom94zoe** [comment]
Hi @IMM9O, 
thank you for your answer. 

It seems like the polyfill for the reflect api was missing. 

fyi.
I set the encapuslation mode to None, otherwise angular material is not working
